cursor            #a7c8ff
cursor_text_color #03305f

background            #111318
foreground            #e1e2e9
selection_foreground  #273141
selection_background  #bdc7dc
url_color             #bdc7dc

#: black
color0  #111318
color8  #32353a

#: red
color1   #ffb4ab
color9  #81b0db

#: green
color2  #a7c8ff
color10 #d9e3f8

#: yellow
color3  #bdc7dc
color11 #dbbde2

#: blue
color4  #234777
color12 #e1e2e9

#: magenta
color5  #3d4758
color13 #bdc7dc

#: cyan
color6   #a7c8ff
color14 #dbbde2

#: white
color7  #ffffff
color15 #dddddd
