font_family                 JetBrains Mono Nerd Font
font_size                   11.0
cursor_shape                beam
cursor_trail                1
cursor_blink_interval       0.5
confirm_os_window_close     0
window_padding_width        5
background                  #0D0D0D
shell                       zsh
