# Font
font_family      JetBrains Mono Nerd Font
font_size 11.0

# Cursor
cursor_shape beam
cursor_trail 1
cursor_blink_interval 0.5

#background
background #24292E
background_opacity 1
window_padding_width 10

#colors
color2 #74aee4
color6 #1793D1