#gaps
gaps inner 5
gaps outer 5

#Disable border for all windows
#for_window [class="^.*"] border pixel 0

#border
default_border pixel 1
default_floating_border pixel 1

#set Color
set $active_border_color #55404b80 
set $active_bg_color     #353535
set $active_text_color   #FFFFFF
set $indicator_color     #424649
client.focused $active_border_color $active_bg_color $active_text_color $indicator_color

# bar {
#        status_command i3status
# }
