source = ~/.config/hypr/hyprland/colors.conf
source = ~/.config/hypr/hyprland/animations.conf
source = ~/.config/hypr/hyprland/keybinds.conf
source = ~/.config/hypr/hyprland/rule.conf

monitor=,preferred,auto,auto

exec-once = $terminal
exec-once = hypridle
exec-once = awww-daemon
exec-once = quickshell

env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24

dwindle {
    pseudotile = true 
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

input {
    kb_layout = us,th
    kb_variant =
    kb_model =
    kb_options = grp:win_space_toggle
    kb_rules =

    follow_mouse = 1

    sensitivity = 0

    touchpad {
        natural_scroll = false
    }
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
