source = ~/.config/hypr/conf.d/general.conf
source = ~/.config/hypr/conf.d/animations.conf
source = ~/.config/hypr/conf.d/keybinds.conf
source = ~/.config/hypr/conf.d/rule.conf

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=,preferred,auto,auto

#Autostart
exec-once = waybar & mako & hyprpaper & swww-daemon & 
exec-once = hyprctl setcursor Bibata-Modern-Classic 24

# See https://wiki.hypr.land/Configuring/Environment-variables/
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Bibata-Modern-Classic
#env = HYPRCURSOR_SIZE,24