$font = JetBrains Mono

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = $HOME/pic/bg.jpg
    background_color = rgba(0, 0, 0, 0.5)

    blur_size = 2
    blur_passes = 1
    brightness = 0.5

}

image {
    monitor = 
    path = $HOME/pic/pf.png
    size = 100
    rounding = 50%

    shadow_passes = 1
    shadow_size = 4
    shadow_color = rgb(0, 0, 0,)
    shadow_boost = 1

    position = 0, 95
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    boder_size = 1
    font_family = $font
    font_size = 17

    shadow_passes = 1
    shadow_size = 4
    shadow_color = rgb(0, 0, 0,)
    shadow_boost = 1

    position = -0, 20
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 2
    inner_color = rgb(28, 28, 28)
    outer_color = rgba(7f9dffee) rgba(5481e9ee) 20deg
    check_color = rgba(00ffe1ee) rgba(33fffcee) 45deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg
    font_color = rgb(143, 143, 143)

    fade_on_empty = false
    rounding = 15
    font_family = $font
    placeholder_text = 󰄛 password... 
    fail_text = $PAMFAIL

    dots_center = true
    dots_size = 0.3
    dots_spacing = 0.4

    shadow_passes = 1
    shadow_size = 4
    shadow_color = rgb(0, 0, 0,)
    shadow_boost = 1

    position = 0, -20
    halign = center
    valign = center
}
