import QtQuick
pragma Singleton

QtObject {
    readonly property color background: "#101418"
    readonly property color error: "#ffb4ab"
    readonly property color error_container: "#93000a"
    readonly property color inverse_on_surface: "#2d3135"
    readonly property color inverse_primary: "#2c638b"
    readonly property color inverse_surface: "#e0e2e8"
    readonly property color on_background: "#e0e2e8"
    readonly property color on_error: "#690005"
    readonly property color on_error_container: "#ffdad6"
    readonly property color on_primary: "#003351"
    readonly property color on_primary_container: "#cce5ff"
    readonly property color on_primary_fixed: "#001d31"
    readonly property color on_primary_fixed_variant: "#074b72"
    readonly property color on_secondary: "#23323f"
    readonly property color on_secondary_container: "#d4e4f6"
    readonly property color on_secondary_fixed: "#0d1d2a"
    readonly property color on_secondary_fixed_variant: "#394857"
    readonly property color on_surface: "#e0e2e8"
    readonly property color on_surface_variant: "#c2c7ce"
    readonly property color on_tertiary: "#372a4a"
    readonly property color on_tertiary_container: "#eddcff"
    readonly property color on_tertiary_fixed: "#221534"
    readonly property color on_tertiary_fixed_variant: "#4e4161"
    readonly property color outline: "#8c9198"
    readonly property color outline_variant: "#42474e"
    readonly property color primary: "#99ccfa"
    readonly property color primary_container: "#074b72"
    readonly property color primary_fixed: "#cce5ff"
    readonly property color primary_fixed_dim: "#99ccfa"
    readonly property color scrim: "#000000"
    readonly property color secondary: "#b8c8da"
    readonly property color secondary_container: "#394857"
    readonly property color secondary_fixed: "#d4e4f6"
    readonly property color secondary_fixed_dim: "#b8c8da"
    readonly property color shadow: "#000000"
    readonly property color source_color: "#88bcea"
    readonly property color surface: "#101418"
    readonly property color surface_bright: "#36393e"
    readonly property color surface_container: "#1c2024"
    readonly property color surface_container_high: "#272a2e"
    readonly property color surface_container_highest: "#313539"
    readonly property color surface_container_low: "#181c20"
    readonly property color surface_container_lowest: "#0b0f12"
    readonly property color surface_dim: "#101418"
    readonly property color surface_tint: "#99ccfa"
    readonly property color surface_variant: "#42474e"
    readonly property color tertiary: "#d1bfe7"
    readonly property color tertiary_container: "#4e4161"
    readonly property color tertiary_fixed: "#eddcff"
    readonly property color tertiary_fixed_dim: "#d1bfe7"
}
