backend = "glx";

#blur: {
#  method = "dual_kawase";
#  strength = 5;
#  background = true;
#};

corner-radius = 10

#shadow
shadow = true;
#shadow-exclude = [
#    "! (class_g = 'Rofi' || class_g = 'kitty')"
#];

#shadow Rofi !
shadow-exclude = [
   "! class_g = 'Rofi'",
];